---
name: Deploy Solution
permissions:
  id-token: write
  contents: write
  actions: write
on:
  push:
    branches:
      - 'test/*'
      - 'uat/*'
      - 'releases/*'

jobs:
  prepare:
    name: 'Prepare environment'
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.env.outputs.env_name }}
    steps:
      - id: env
        run: |
          BRANCH="${GITHUB_REF_NAME}"
    
          if [[ $BRANCH == dev/* ]]; then
            ENV_NAME="DEV"
          elif [[ $BRANCH == test/* ]]; then
            ENV_NAME="TEST"
          elif [[ $BRANCH == uat/* ]]; then
            ENV_NAME="UAT"
          elif [[ $BRANCH == releases/* ]]; then
            ENV_NAME="PROD"
          else
            echo "Invalid branch naming"
            exit 1
          fi
  
          echo "env_name=$ENV_NAME" >> $GITHUB_OUTPUT
          echo "### Using environment $ENV_NAME" >> $GITHUB_STEP_SUMMARY

  set:
    name: Set Target Environment
    runs-on: ubuntu-latest
    needs: prepare
    environment: ${{ needs.prepare.outputs.env_name }}
    outputs:
      pp_env_url: ${{ steps.set.outputs.pp_env_url }}
      sp_site_url: ${{ steps.set.outputs.sp_site_url }}
    steps:
      - id: set
        run: |
          echo "pp_env_url=${{ vars.PP_ENV_URL }}" >> $GITHUB_OUTPUT
          echo "sp_site_url=${{ vars.SP_SITE_URL }}" >> $GITHUB_OUTPUT
          
  # sharepoint-remote-job:
  #   name: SharePoint
  #   needs: set
  #  uses: gpjspr/gpj-common/.github/workflows/sp-update-schema-bsispdev.yml@main
  #  with:
  #    solutionname: ${{ vars.PP_SOLUTION_NAME }}
  #    siteurl:  ${{ needs.set.outputs.sp_site_url }}
      
  solution-remote-job:
    name: Solution
 
    needs: set
    uses: gpjspr/gpj-common/.github/workflows/pp-deploy-bsispdev.yml@main
    with:
      solutionname: ${{ vars.PP_SOLUTION_NAME }}
      pp_env_url: ${{ needs.set.outputs.pp_env_url }}
  
