---
name: 'Get Unpack Store Solution'
permissions: 
  id-token: write
  contents: write

on:
  workflow_dispatch:
    inputs:
      solutionname:
        description: 'The power platform solution name'
        required: false
        default: UkCustomsApp
        type: string
      major:
        description: 'The major version (the first solution number). If left blank, the current major version will be used.'
        required: false
        type: number
      minor:
        description: 'The minor version (the second solution number). If left blank, the current minor version will be used.'
        required: false
        type: number
jobs:
  export-solution-remote-job:
    name: Get Unpack Store Solution
    uses: gpjspr/gpj-common/.github/workflows/pp-get-unpack-store-bsispdev.yml@main
    with:
      solutionname: ${{ inputs.solutionname}}
      major: ${{inputs.major}}
      minor: ${{inputs.minor}}

  lint-canvasapps-remote-job:
    name: Check Canvas Apps
    uses: gpjspr/gpj-common/.github/workflows/pp-canvasapp-lint.yml@main
    with:
      fail-on-errors: false
    needs: export-solution-remote-job

  document-flows-remote-job:
    name: Document Flows
    uses: gpjspr/gpj-common/.github/workflows/pp-document-flows.yml@main
    with:
      flow-path: src/solutions/${{ inputs.solutionname }}/Workflows
      output-path: documentation/flowdiagrams
    needs: export-solution-remote-job
