---
name: 'Update SharePoint Schema'
permissions: 
  id-token: write
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Deployment environment'
        options:
          - TEST
          - UAT
          - PROD

jobs:    
  set:
    name: 'Prepare environment variables'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      sp_site_url: ${{ steps.set.outputs.sp_site_url }}
  
    steps:
      - id: set
        run: |
          echo "sp_site_url=${{ vars.SP_SITE_URL }}" >> $GITHUB_OUTPUT
          echo "### Using environment ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "Site =  ${{ vars.SP_SITE_URL }}" >> $GITHUB_STEP_SUMMARY 
  call-remote-job:
    name: SharePoint
    needs: set
    uses: gpjspr/gpj-common/.github/workflows/sp-update-schema-bsispdev.yml@main
    with:
      solutionname: ${{ vars.PP_SOLUTION_NAME }}
      siteurl:  ${{ needs.set.outputs.sp_site_url }}
