---
name: 'Get SharePoint Schema'
permissions: 
  id-token: write
  contents: write

on:
  workflow_dispatch:
    inputs:
      arguments:
        description: 'Optional arguments for PnP such as -Handlers Lists'
        required: false
        default: ''
        type: string

jobs:
  prepare:
    name: 'Prepare environment variables'
    runs-on: ubuntu-latest
    environment: DEV
    outputs:
      sp_site_url: ${{ steps.set.outputs.sp_site_url }}

    steps:
      - id: set
        run: |
          echo "sp_site_url=${{ vars.SP_SITE_URL }}" >> $GITHUB_OUTPUT
          
  call-remote-job:
    name: SharePoint
    needs: prepare
    uses: gpjspr/gpj-common/.github/workflows/sp-get-schema-bsispdev.yml@main
    with:
      solutionname: ${{ vars.PP_SOLUTION_NAME }}
      siteurl:  ${{ needs.prepare.outputs.sp_site_url }}
      arguments: ${{ inputs.arguments }}
